### ISSUE TITLE
First app state action is fired before redux-saga is initialized

### ISSUE THREAD

**Issue by cniaulin** [bamlab/redux-enhancer-react-native-appstate#5]
Just wanted to try redux-enhancer-react-native-appstate with redux-saga however, it seems the first app state event "APP_STATE.FOREGROUND" seems to be fired before redux-saga is initialized and so redux-saga misses this action.

**Comment by cniaulin** [comment]
Just made a small fix for it. 

#6

**Comment by Almouro** [comment]
Fix published with v0.3.1 so closing this, thanks @cniaulin!
